name: md3nlp_2020
channels:
  - defaults
dependencies:
  - python=3.7
  - spacy=2.2.2
  - numpy
  - pandas
  - pip
  - matplotlib
  - spacy
  - pip:
    - pymysql
    - cycontext
    - ibis-framework[mysql]
    - clinical-sectionizer=0.1.2
    - medspacy=0.0.1
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz \
    - https://github.com/abchapman93/spacy_models/raw/master/releases/en_info_3700_i2b2_2012-0.1.0/dist/en_info_3700_i2b2_2012-0.1.0.tar.gz

